    <script src="{{url('public')}}/vendor/jquery/jquery.min.js"></script>
    <script src="{{url('public')}}/vendor/popper.js/umd/popper.min.js"> </script>
    <script src="{{url('public')}}/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="{{url('public')}}/vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="{{url('public')}}/vendor/waypoints/lib/jquery.waypoints.min.js"> </script>
    <script src="{{url('public')}}/vendor/jquery.counterup/jquery.counterup.min.js"> </script>
    <script src="{{url('public')}}/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="{{url('public')}}/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js"></script>
    <script src="{{url('public')}}/js/jquery.parallax-1.1.3.js"></script>
    <script src="{{url('public')}}/vendor/bootstrap-select/js/bootstrap-select.min.js"></script>
    <script src="{{url('public')}}/vendor/jquery.scrollto/jquery.scrollTo.min.js"></script>
    <script src="{{url('public')}}/js/front.js"></script>